TRAIN_IMAGE_PATH = './train/images/'
TEST_IMAGE_PATH = './test/images/'

TRAIN_FONTS_PATH = './train/fonts/'
TEST_FONTS_PATH = './test/fonts/'

TRAIN_CSV_PATH = './train/label.csv'
TEST_CSV_PATH = './test/label.csv'

SAVED_MODEL_PATH = './saved_models/'
PRETRAINED_MODEL_PATH = './pretrained_models/'
LABEL_PATH = './train/labels.txt'

#IMAGE GENERATION PARAMETER VALUE
IMAGE_WIDTH = IMAGE_HEIGHT = 64
FONT_SIZE = 48
BACKGROUND = 0
FONT_COLOR = (255,255,255)
DISTORTION_TIMES = 4
ALPHA_MIN = 40
ALPHA_MAX = 45
SIGMA_MIN = 6
SIGMA_MAX = 7
BLUR_EXTENT = 2
ROTATION_ANGLE = 20


#HYPERPAMETER AND CONFIGURATION
CUDA = True
MULTI_GPUS = False
LEARING_RATE = 0.0001
BATCH = 64
TRAIN_IMAGE_SIZE = 224
EPOCH = 10
NUM_CLASSES = 2421